(() => {
  'use strict';
  const KEY='campus.web.v1', TZ='Asia/Seoul';
  const WEEK='https://kisj.powerschool.com/guardian/myschedule.html';
  const MATRIX='https://kisj.powerschool.com/guardian/myschedulematrix.html';
  const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday'];
  const SHORT=['Mon','Tue','Wed','Thu','Fri'];
  const KEYS=PowerSchoolImport.dayKeys;
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
  const icons={sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',check:'<path d="M8 6h13M8 12h13M8 18h13M2 6l1 1 2-2M2 12l1 1 2-2M2 18l1 1 2-2"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/>',meal:'<path d="M4 2v8a3 3 0 0 0 6 0V2M7 2v20M18 2c-4 4-4 11 0 12v8"/>',trash:'<path d="M4 7h16M9 7V4h6v3m-9 0 1 14h10l1-14M10 11v6m4-6v6"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v6m0-9h.01"/>',gear:'<circle cx="12" cy="12" r="3"/><path d="m19.5 12 2-1-2-4-2 1-2-2-1-2h-4l-1 2-2 2-2-1-2-4 2-1-2-2 2-4 2 1 2-2 1-2h4l1 2 2 2 2-1 2 4-2 2Z"/>',plus:'<path d="M12 5v14M5 12h14"/>',sync:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M5 9a8 8 0 0 1 14-2l1 5M4 12l1 5a8 8 0 0 0 14-2"/>',alert:'<circle cx="12" cy="12" r="9"/><path d="M12 7v6m0 4h.01"/>',external:'<path d="M14 4h6v6m0-6-9 9"/><path d="M20 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5"/>'};
  const icon=(name,cls='')=>`<svg class="${cls}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]||icons.info}</svg>`;
  const defaults=()=>({version:1,setupComplete:false,setupStep:0,division:'MS',appearance:'system',schedules:{},rotation:null,homework:[],events:[],remoteEvents:[],remoteUpdated:null,eventOverrides:{},club:{enabled:false,name:'Club',days:[1,3],start:'15:30',end:'16:00'},customDays:{},cafeteria:{},trash:[],savedTemplates:[],dismissedClassroomKeys:[],googleReconnectRequired:false});
  let state;
  try{state={...defaults(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{state=defaults()}
  const parts=(date=new Date())=>Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date).filter(p=>p.type!=='literal').map(p=>[p.type,p.value]));
  let page=(location.hash||'#today').slice(1),weekdayView=0,rotationView='A',scheduleMode='regular',customDate=dateKey(),homeworkTab='todo',selecting=false,selection=new Set(),monthView=dateKey().slice(0,7),draft={week:null,matrix:null,error:''},cafeteriaStatus='',pendingTransfer=null,pendingTransferNonce=null;
  const pages=[['today','Today','sun'],['schedule','Schedule','clock'],['homework','Homework','check'],['calendar','Calendar','calendar'],['cafeteria','Cafeteria','meal'],['trash','Trash','trash'],['about','About','info']];
  if(!pages.some(p=>p[0]===page)&&page!=='settings')page='today';
  function dateKey(date=new Date()){const p=parts(date);return `${p.year}-${p.month}-${p.day}`}
  const dateObj=iso=>new Date(`${iso}T12:00:00Z`);
  const dateLabel=iso=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',timeZone:'UTC'}).format(dateObj(iso));
  const dateTime=iso=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:TZ}).format(new Date(iso));
  const dayIndex=iso=>PowerSchoolImport.weekdayIndex(iso);
  const plusDays=(iso,n)=>PowerSchoolImport.addDays(iso,n);
  const minutes=t=>Number(t?.slice(0,2))*60+Number(t?.slice(3,5));
  const hex=s=>/^#[\da-f]{6}$/i.test(s||'');
  const validDate=text=>{const m=String(text||'').match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(!m)return null;const iso=`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const date=dateObj(iso);return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===iso?iso:null};
  let toastTimer;
  function toast(message){$('#toast-root').innerHTML=`<div class="toast">${esc(message)}</div>`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast-root').innerHTML='',4200)}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{toast('Browser storage is full. This change could not be saved.');return false}}
  const allEvents=()=>[...state.remoteEvents.map(e=>({...e,...(state.eventOverrides[e.id]||{})})),...state.events];
  const covers=(e,iso)=>e.start<=iso&&(e.end||e.start)>=iso;
  const effect=(iso,type)=>allEvents().some(e=>e.type===type&&covers(e,iso));
  function rotationAt(iso){if(!state.rotation||dayIndex(iso)>4)return null;let day=state.rotation.date,n=0,dir=iso>=day?1:-1,guard=0;while(day!==iso&&guard++<1400){day=plusDays(day,dir);if(dayIndex(day)<5)n++}if(guard>=1400)return null;return n%2?(state.rotation.day==='A'?'B':'A'):state.rotation.day}
  function scheduleKey(iso){const day=rotationAt(iso),index=dayIndex(iso);return day&&index<5?KEYS[index*2+(day==='B'?1:0)]:null}
  function lastFriday(iso){return dayIndex(iso)===4&&plusDays(iso,7).slice(0,7)!==iso.slice(0,7)}
  const lateTimes=[['10:00','10:40'],['10:45','11:25'],['11:30','12:10'],['12:10','12:45'],['12:45','13:25'],['13:30','14:10'],['14:15','14:55'],['15:00','15:40']];
  function classesOn(iso){
    if(dayIndex(iso)>4||effect(iso,'break'))return[];
    const custom=state.customDays[iso];
    let list=(custom?.classes||state.schedules[scheduleKey(iso)]||[]).map(c=>({...c})).sort((a,b)=>minutes(a.start)-minutes(b.start));
    if(!custom&&(effect(iso,'late')||lastFriday(iso))&&list.length){
      const lunch=list.find(c=>/lunch/i.test(c.subject));
      const queue=list.filter(c=>!/lunch/i.test(c.subject));
      list=lateTimes.flatMap(([start,end],i)=>{
        const block=i===3?lunch||{id:'lunch',subject:'Lunch',teacher:'',room:''}:queue.shift();
        return block?[{...block,start,end}]:[];
      });
    }
    if(state.club.enabled&&state.club.days.includes(dayIndex(iso)))list.push({id:'club',subject:state.club.name||'Club',teacher:'',room:'',start:state.club.start,end:state.club.end});
    list.sort((a,b)=>minutes(a.start)-minutes(b.start));
    if(effect(iso,'half')){const lunch=list.find(c=>/lunch/i.test(c.subject));return lunch?list.filter(c=>minutes(c.end)<=minutes(lunch.end)):[]}
    return list;
  }
  const dueSoon=()=>state.homework.filter(h=>!h.complete&&new Date(h.due).getTime()>=Date.now()&&new Date(h.due).getTime()<=Date.now()+86400000).sort((a,b)=>a.due.localeCompare(b.due));
  function badge(h){const ms=new Date(h.due).getTime()-Date.now();if(ms<0)return'<span class="pill red">OVERDUE</span>';if(ms<3600000)return'<span class="pill red">IMMEDIATE</span>';if(ms<86400000)return'<span class="pill orange">24HR</span>';if(ms<172800000)return'<span class="pill yellow">SOON</span>';const m=Math.floor(ms/60000);return`<span class="pill">${String(Math.floor(m/1440)).padStart(2,'0')}:${String(Math.floor(m%1440/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}</span>`}
  const card=(title,symbol,content,extra='')=>`<section class="card"><div class="card-head"><div class="card-title">${icon(symbol,'card-icon')}<span class="micro">${esc(title)}</span></div>${extra}</div>${content}</section>`;
  const empty=text=>`<div class="empty">${icon('info')}${esc(text)}</div>`;
  const header=(title,subtitle,actions='')=>`<div class="page-head"><div><h1 class="page-title">${esc(title)}</h1>${subtitle?`<p class="page-subtitle">${esc(subtitle)}</p>`:''}</div>${actions?`<div class="page-actions">${actions}</div>`:''}</div>`;
  function onboardingView(){
    const step=Math.max(0,Math.min(2,Number(state.setupStep)||0));
    const trail=`<div class="setup-trail">${['Your school','PowerSchool','Google Classroom'].map((label,i)=>`<div class="setup-trail-item ${i===step?'current':''} ${i<step?'passed':''}"><span>${i+1}</span>${label}</div>`).join('')}</div>`;
    const heading=step===0?['Make Campus yours','Choose your school division. You can change this later.']:step===1?['Bring in your schedule',state.division==='MS'?'For Middle School, Matrix View is all you need. Campus applies the fixed MS bell times.':'Copy Week View for times and Matrix View for courses.']:['Homework, all in one place','Google Classroom connection can be added after web OAuth is configured. Manual homework is ready now.'];
    const body=step===0?`<div class="setup-choices">${[['ES','Elementary School'],['MS','Middle School'],['HS','High School']].map(([id,label])=>`<button class="setup-choice ${state.division===id?'selected':''}" data-action="setup-division" data-division="${id}"><span class="setup-choice-letter">${id}</span><span><strong>${label}</strong><small>${id==='MS'?'Matrix-only PowerSchool import':'Week + Matrix PowerSchool import'}</small></span><span class="setup-choice-indicator">${state.division===id?'✓':''}</span></button>`).join('')}</div><div class="form-actions"><button class="btn primary" data-action="setup-next">Continue</button></div>`:step===1?`<div class="setup-feature">${icon('clock')}<div><strong>${state.division==='MS'?'One page, ten schedules':'Two pages, ten schedules'}</strong><p>${state.division==='MS'?'Copy Matrix View. Weekday class times are filled automatically; each can be edited later. Tuesday and Thursday Club defaults to 15:30–16:00.':'Campus combines the times in Week View with the ten A/B schedules in Matrix View.'}</p></div></div>${state.rotation?`<div class="notice success">Synced all 10 A/B schedules.</div>`:''}<div class="form-actions"><button class="btn" data-action="setup-back">Back</button><button class="btn" data-action="setup-skip">Do this later</button><button class="btn primary" data-action="sync">${state.rotation?'Redo Sync':'Sync PowerSchool'}</button>${state.rotation?'<button class="btn primary" data-action="setup-next">Continue</button>':''}</div>`:`<div class="setup-feature">${icon('check')}<div><strong>Connect Google Classroom</strong><p>Your homework syncs here after Google sign-in. You can also finish without connecting.</p></div></div><div class="form-actions"><button class="btn" data-action="setup-back">Back</button><button class="btn" data-action="google-info">Connect Google</button><button class="btn primary" data-action="setup-finish">Finish setup</button></div>`;
    const transfer=step===0?`<div class="setup-transfer"><div><strong>Already use Campus on Mac?</strong><p class="small muted">Import your Mac schedules, homework, custom days, club and personal calendar events. Campus will open through its app link and ask before sending.</p></div><button class="btn" data-action="import-from-app">Import from Mac app</button></div>`:'';
    return `<div class="setup-page"><div class="setup-overline">WELCOME TO CAMPUS</div>${trail}<section class="card setup-card"><div class="setup-icon">${icon(step===0?'info':step===1?'clock':'check')}</div><div class="micro">STEP ${step+1} OF 3</div><h1>${heading[0]}</h1><p class="setup-intro">${heading[1]}</p>${transfer}${body}</section><p class="setup-footnote">Your schedule and personal data stay in this browser.</p></div>`;
  }
  const typeLabel=t=>({break:'No school',half:'Half day',info:'Information',late:'Late start'})[t]||'Event';
  function theme(){document.body.dataset.theme=state.appearance==='dark'||(state.appearance==='system'&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light'}
  function nav(){const el=$('#navigation');el.innerHTML=pages.map(([id,title,symbol],i)=>`${i===1?'<div class="nav-heading">Plan</div>':i===4?'<div class="nav-heading">School</div>':''}<button class="nav-item ${page===id?'active':''}" data-nav="${id}">${icon(symbol,'nav-icon')}<span>${title}</span>${id==='trash'&&state.trash.length?`<span class="nav-badge">${state.trash.length}</span>`:''}</button>`).join('');$('#settings-button').innerHTML=icon('gear','nav-icon')+'<span>Settings</span>';$('#settings-button').classList.toggle('active',page==='settings')}
  function render(){theme();document.body.classList.toggle('onboarding',!state.setupComplete);if(!state.setupComplete){$('#topbar-meta').textContent=`Setup · ${Math.max(0,Math.min(2,Number(state.setupStep)||0))+1} of 3`;$('#view').innerHTML=onboardingView();return}nav();$('#topbar-meta').textContent=state.rotation?`${state.division} · ${rotationAt(dateKey())||'No school'} Day`:state.division+' · Local only';$('#view').innerHTML=({today:todayView,schedule:scheduleView,homework:homeworkView,calendar:calendarView,cafeteria:cafeteriaView,trash:trashView,about:aboutView,settings:settingsView}[page]||todayView)()}
  function go(name){page=name;location.hash=name;render();$('#view').focus({preventScroll:true});$('#view').scrollTop=0;requestAnimationFrame(()=>$('#view').scrollTop=0);$('.sidebar').classList.remove('open')}
  function countdown(target){const p=parts(),sec=Math.max(0,(target-Number(p.hour)*60-Number(p.minute))*60-Number(p.second));return`${String(Math.floor(sec/3600)).padStart(2,'0')}:${String(Math.floor(sec%3600/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
  function todayView(){const iso=dateKey(),p=parts(),now=Number(p.hour)*60+Number(p.minute),classes=classesOn(iso),current=classes.find(c=>minutes(c.start)<=now&&now<minutes(c.end)),next=classes.find(c=>minutes(c.start)>now),due=dueSoon(),upcoming=allEvents().filter(e=>(e.end||e.start)>=iso).sort((a,b)=>a.start.localeCompare(b.start)).slice(0,4),menu=state.cafeteria[state.division];const cell=(title,c,until)=>`<div><div class="micro">${title}</div>${c?`<button class="inline-class" data-action="show-day"><span class="big-class">${esc(c.subject)}</span><span>›</span></button><div class="small muted">${esc([c.room,c.teacher].filter(Boolean).join(' · ')||'No room or teacher set')}</div><div class="small faint" style="margin-top:6px">${esc(c.start)} – ${esc(c.end)}</div><div class="countdown" style="margin-top:12px">${until?'Ends':'Begins'} in ${countdown(minutes(until?c.end:c.start))}</div>${until?`<div class="progress"><span style="width:${Math.max(0,Math.min(100,100*(now-minutes(c.start))/(minutes(c.end)-minutes(c.start))))}%"></span></div>`:''}`:`<div class="big-class">${title==='Right Now'?'No class':'Done'}</div><div class="small muted">${effect(iso,'break')?'School break today.':!state.rotation?'Import your schedule to see your day.':title==='Right Now'?'Campus will watch for your next class.':'No more classes scheduled today.'}</div>`}</div>`;return header('Today',new Intl.DateTimeFormat('en-US',{timeZone:TZ,dateStyle:'full'}).format(new Date()))+`<div class="stack">${card('Now / Next','clock',`<div class="grid-2 now-next">${cell('Right Now',current,true)}${cell('Up Next',next,false)}</div>`)}${card('Due Next 24 Hours','alert',due.length?due.map(h=>`<div class="row"><div class="row-main"><div class="row-title">${esc(h.title)}</div><div class="row-sub">${esc(h.subject||'Homework')} · ${dateTime(h.due)}</div></div>${badge(h)}</div>`).join(''):empty('Nothing due in the next 24 hours.'))}<div class="grid-2">${card('Cafeteria','meal',menu?.image?`<img class="menu-image" style="max-height:260px" src="${esc(menu.image)}" alt="Cached ${esc(state.division)} lunch menu"><p class="small faint">Cached ${dateTime(menu.fetchedAt)}</p>`:empty('No cached menu image.'),'<button class="btn small" data-nav="cafeteria">Open</button>')}${card('Calendar','calendar',upcoming.length?upcoming.map(e=>`<div class="row"><span class="color-dot" style="background:${hex(e.color)?e.color:'#333'}"></span><div class="row-main"><div class="row-title">${esc(e.title)}</div><div class="row-sub">${dateLabel(e.start)} · ${typeLabel(e.type)}</div></div></div>`).join(''):empty('No upcoming events.'),'<button class="btn small" data-nav="calendar">Open</button>')}</div></div>`}
  function classRow(c,key){return`<div class="class-row" style="--class-color:${hex(c.color)?c.color:'transparent'}"><div class="class-row-title"><span class="class-name">${esc(c.subject)}</span>${c.id==='club'?'<span class="pill">CLUB</span>':''}<button class="btn small class-edit" data-action="${c.id==='club'?'mode':'class-edit'}" ${c.id==='club'?'data-mode="club"':`data-key="${esc(key)}" data-id="${esc(c.id)}"`}>Edit</button></div><div class="class-meta-grid"><span>Teacher</span><strong>${esc(c.teacher||'—')}</strong><span>Room</span><strong>${esc(c.room||'—')}</strong><span>Start</span><strong>${esc(c.start)}</strong><span>End</span><strong>${esc(c.end)}</strong></div></div>`}
  function scheduleView(){const synced=state.rotation?.lastSyncedAt;if(!Object.keys(state.schedules).length&&scheduleMode==='regular')return header('Schedule','Set up your school schedule.')+`<section class="first-sync"><button class="btn primary" data-action="sync">${icon('sync')}Automatically Sync Powerschool</button><button class="text-link" data-action="manual-start">or manually put everything</button></section>`;const modeTabs=`<div class="schedule-controls"><div class="tabs mode-tabs">${[['regular','A Day','A'],['regular','B Day','B'],['club','Club',''],['custom','Custom Day','']].map(([mode,title,day])=>`<button class="tab ${(scheduleMode===mode&&(mode!=='regular'||rotationView===day))?'active':''}" data-action="schedule-tab" data-mode="${mode}" data-day="${day}">${title}</button>`).join('')}</div><div class="schedule-actions"><button class="btn" data-action="sync">${icon('sync')}PowerSchool Sync</button>${scheduleMode!=='club'?`<button class="btn primary" data-action="${scheduleMode==='custom'?'custom-add':'class-new'}">${icon('plus')}Add Class</button>`:''}</div></div>`;return header('Schedule','Manage weekday A/B schedules, Club, and custom days.')+modeTabs+(scheduleMode==='club'?clubView():scheduleMode==='custom'?customView():regularView())+`<div class="schedule-footer"><span>${synced?`PowerSchool synced ${dateTime(synced)}`:'A/B rotation is calculated Monday–Friday from the current reference day.'}</span><span>The current class is highlighted automatically.</span></div>`}
  function regularView(){const key=KEYS[weekdayView*2+(rotationView==='B'?1:0)],classes=[...(state.schedules[key]||[])];if(state.club.enabled&&state.club.days.includes(weekdayView))classes.push({id:'club',subject:state.club.name||'Club',teacher:'',room:'',start:state.club.start,end:state.club.end});return`<div class="weekday-control"><span class="micro">Weekday</span><div class="tabs weekday-tabs">${SHORT.map((d,i)=>`<button class="tab ${weekdayView===i?'active':''}" data-action="weekday" data-index="${i}">${d}</button>`).join('')}</div><span class="weekday-summary">${DAYS[weekdayView]} · ${rotationView}</span></div><div class="schedule-list-panel">${classes.length?`<div class="schedule-list">${classes.sort((a,b)=>minutes(a.start)-minutes(b.start)).map(c=>classRow(c,key)).join('')}</div>`:empty('No classes yet for this day.')}</div><div class="rotation-reference"><span class="micro">A/B reference day</span><input type="date" id="anchor-date" value="${esc(state.rotation?.date||dateKey())}" aria-label="Known date"><select id="anchor-day" aria-label="Known A/B day"><option ${state.rotation?.day==='A'?'selected':''}>A</option><option ${state.rotation?.day==='B'?'selected':''}>B</option></select><button class="btn" data-action="anchor-save">Save</button></div>`}
  function clubView(){const c=state.club;return card('Club schedule','calendar',`<p class="small muted">Your club class appears on the selected weekdays, independent of A/B rotation.</p><form id="club-form"><label class="switch-line"><input type="checkbox" name="enabled" ${c.enabled?'checked':''}> Enable Club</label><div class="field" style="margin-top:15px"><label>Club name</label><input name="name" value="${esc(c.name)}" placeholder="Club"></div><div class="field"><label>Days</label><div class="weekday-tabs">${SHORT.map((d,i)=>`<label class="choice-chip"><input type="checkbox" name="day" value="${i}" ${c.days.includes(i)?'checked':''}> ${d}</label>`).join('')}</div></div><div class="form-grid"><div class="field"><label>Starts</label><input type="time" name="start" value="${esc(c.start)}"></div><div class="field"><label>Ends</label><input type="time" name="end" value="${esc(c.end)}"></div></div><div class="form-actions"><button class="btn primary">Save Club</button></div></form>`)}
  function customView(){const day=state.customDays[customDate];return`<div class="schedule-toolbar"><div class="anchor-row"><label for="custom-date">Date</label><input type="date" id="custom-date" value="${esc(customDate)}"></div><div class="page-actions"><button class="btn" data-action="custom-copy">Use normal schedule</button><button class="btn primary" data-action="custom-add">${icon('plus')}Add Class</button>${day?'<button class="btn danger" data-action="custom-remove">Remove Custom Day</button>':''}</div></div>${card(day?.title||'Custom Day','clock',day?day.classes.length?`<div class="schedule-list">${day.classes.map(c=>classRow(c,`custom:${customDate}`)).join('')}</div>`:empty('No classes added for this custom day.'):empty('No custom schedule saved for this date.'))}`}
  function homeworkView(){
    const todo=state.homework.filter(h=>!h.complete),done=state.homework.filter(h=>h.complete);
    const list=(homeworkTab==='todo'?todo:done).sort((a,b)=>a.due.localeCompare(b.due));
    const tools=selecting?`<div class="selection-tools"><span class="small muted">${selection.size} selected</span><button class="btn" data-action="bulk-done">Mark done</button><button class="btn" data-action="bulk-color">Color</button><button class="btn danger" data-action="bulk-trash">${icon('trash')}Delete</button><button class="btn primary" data-action="select-end">Done</button></div>`:`<div class="selection-tools"><span class="small faint">${list.length} assignments</span><button class="btn" data-action="select-start">${icon('check')}Select</button><button class="btn primary" data-action="hw-new">${icon('plus')}Add Homework</button></div>`;
    const rows=list.length?list.map(h=>`<div class="homework-row" style="--assignment-color:${hex(h.color)?h.color:'#e0e0df'}"><span class="assignment-accent"></span>${selecting?'':`<button class="delete-icon" data-action="hw-trash" data-id="${esc(h.id)}" aria-label="Move ${esc(h.title)} to Trash">${icon('trash')}</button>`}<label class="check-hit"><input class="check" type="checkbox" data-change="${selecting?'select-hw':'complete-hw'}" data-id="${esc(h.id)}" ${selecting?selection.has(h.id)?'checked':'':h.complete?'checked':''} aria-label="${selecting?'Select':'Mark done'} ${esc(h.title)}"><span class="check-visual"></span></label><button class="homework-main ${h.complete?'completed':''}" data-action="hw-edit" data-id="${esc(h.id)}"><span class="row-title">${esc(h.title)}</span><span class="row-sub">${esc(h.subject||'Homework')} · ${dateTime(h.due)} · ${/google/i.test(h.source||'')?'Google Classroom':'Manual'}</span>${h.note?`<span class="row-note">${esc(h.note)}</span>`:''}</button>${h.complete?'<span class="pill">DONE</span>':badge(h)}${h.url&&!selecting?`<a class="btn shortcut" href="${esc(h.url)}" target="_blank" rel="noopener noreferrer">Open ${icon('external')}</a>`:''}</div>`).join(''):empty(homeworkTab==='todo'?'No homework to do. Connect Google Classroom or add an assignment manually.':'No completed homework. Uncheck it to move it back to To do.');
    const reconnect=state.googleReconnectRequired&&!CampusGoogle.connected()?'<div class="notice">Google Classroom sign-in was not transferred from the Mac app. Connect Google here again to resume homework sync.</div>':'';
    return header('Homework','Assignments from Google Classroom and manual entries.')+reconnect+`<div class="homework-layout"><section class="card classroom-panel"><div class="card-head"><div class="card-title">${icon('check','card-icon')}<span class="micro">Google Classroom</span></div></div><p class="small muted">${CampusGoogle.connected()?`Connected${state.googleLastSync?` · Synced ${dateTime(state.googleLastSync)}`:""}`:"Google Classroom is not connected."}</p><button class="btn primary" data-action="google-info">${CampusGoogle.connected()?"Sync Google":"Connect Google"}</button></section><div class="assignments-panel"><div class="tabs homework-tabs"><button class="tab ${homeworkTab==='todo'?'active':''}" data-action="hw-tab" data-tab="todo">To do (${todo.length})</button><button class="tab ${homeworkTab==='done'?'active':''}" data-action="hw-tab" data-tab="done">Completed (${done.length})</button></div><div class="assignment-toolbar">${tools}</div><div class="assignment-list">${rows}</div></div></div>`;
  }
  function calendarView(){
    const [year,month]=monthView.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1,12));
    const offset=first.getUTCDay(),count=new Date(Date.UTC(year,month,0)).getUTCDate();
    const cellCount=Math.ceil((offset+count)/7)*7,events=allEvents(),today=dateKey();
    const weeks=Array.from({length:cellCount/7},(_,week)=>{
      const days=Array.from({length:7},(_,column)=>{const iso=plusDays(`${monthView}-01`,week*7+column-offset);return iso.startsWith(monthView)?iso:null});
      const occupied=[],segments=[];
      events.filter(e=>days.some(iso=>iso&&covers(e,iso))).sort((a,b)=>a.start.localeCompare(b.start)||((b.end||b.start).localeCompare(a.end||a.start))).forEach(e=>{
        const columns=days.map((iso,i)=>iso&&covers(e,iso)?i:-1).filter(i=>i>=0),start=columns[0],end=columns.at(-1);
        let lane=occupied.findIndex(ranges=>ranges.every(([a,b])=>end<a||start>b));
        if(lane<0){lane=occupied.length;occupied.push([])}
        occupied[lane].push([start,end]);segments.push({event:e,start,end,lane,continuesBefore:e.start<days[start],continuesAfter:(e.end||e.start)>days[end]});
      });
      const cells=days.map(iso=>{if(!iso)return'<div class="calendar-cell outside" aria-hidden="true"></div>';
        const due=state.homework.filter(h=>dateKey(new Date(h.due))===iso);
        return`<div class="calendar-cell ${iso===today?'today':''}"><span class="calendar-date">${Number(iso.slice(-2))}</span><div class="calendar-event-space" style="height:${occupied.length*24}px"></div>${due.slice(0,2).map(h=>`<button class="calendar-due ${h.complete?'completed':''}" data-action="hw-edit" data-id="${esc(h.id)}" title="${esc(h.title)} due">${icon(h.complete?'check':'calendar')}${esc(h.title)} due</button>`).join('')}${due.length>2?`<div class="calendar-more">+${due.length-2} due</div>`:''}</div>`;
      }).join('');
      const bands=segments.map(({event,start,end,lane,continuesBefore,continuesAfter})=>`<button class="calendar-band ${continuesBefore?'continues-before':''} ${continuesAfter?'continues-after':''}" style="grid-column:${start+1}/${end+2};grid-row:${lane+1};background:${hex(event.color)?event.color:'#292a2c'};color:${hex(event.color)?colorText(event.color):'#fff'}" data-action="event-edit" data-id="${esc(event.id)}" title="${esc(event.title)}">${esc(event.title)}</button>`).join('');
      return`<div class="calendar-week">${cells}<div class="calendar-band-layer" style="grid-template-rows:repeat(${occupied.length||1},24px)">${bands}</div></div>`;
    }).join('');
    const monthTitle=new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'long',year:'numeric'}).format(first);
    return header(monthTitle,`Today is ${new Intl.DateTimeFormat('en-US',{timeZone:TZ,dateStyle:'full'}).format(new Date())}`,`<button class="btn icon-only" data-action="calendar-refresh" aria-label="Refresh school calendar">${icon('sync')}</button><button class="btn icon-only" data-action="month-prev" aria-label="Previous month">‹</button><button class="btn icon-only" data-action="month-today" aria-label="Jump to today">⌖</button><button class="btn icon-only" data-action="month-next" aria-label="Next month">›</button><button class="btn primary" data-action="event-new">${icon('plus')}Add</button><a class="btn" href="https://kis.ac/school-calendar/" target="_blank" rel="noopener noreferrer">KIS</a>`)+`<section class="card calendar-card"><div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<span class="calendar-label">${d}</span>`).join('')}</div><div class="calendar-weeks">${weeks}</div></section>`;
  }
  function colorText(s){const v=s.slice(1),lum=.2126*parseInt(v.slice(0,2),16)+.7152*parseInt(v.slice(2,4),16)+.0722*parseInt(v.slice(4,6),16);return lum>145?'#202124':'#fff'}
  function cafeteriaView(){const menu=state.cafeteria[state.division];return header('Cafeteria','Latest KIS menu image',`<select id="division-select" aria-label="School division">${['ES','MS','HS'].map(d=>`<option ${state.division===d?'selected':''}>${d}</option>`).join('')}</select><button class="btn" data-action="cafe-refresh">${icon('sync')}Refresh</button>`)+card(`${state.division} Lunch Menu`,'meal',(menu?.image?`<img class="menu-image" src="${esc(menu.image)}" alt="${esc(state.division)} cafeteria menu"><p class="small faint">Updated ${dateTime(menu.fetchedAt)}</p>`:empty('No menu image is available yet.'))+(cafeteriaStatus?`<div class="notice" style="margin-top:14px">${esc(cafeteriaStatus)}</div>`:''))}
  function trashView(){return header('Trash',`${state.trash.length} saved item${state.trash.length===1?'':'s'}`,state.trash.length?'<button class="btn danger" data-action="trash-clear">Empty Trash</button>':'')+card('Recently deleted','trash',state.trash.length?state.trash.map(item=>`<div class="row"><div class="row-main"><div class="row-title">${esc(item.title)}</div><div class="row-sub">${esc(item.type)} · ${dateTime(item.deletedAt)}</div></div><button class="btn small" data-action="trash-restore" data-id="${esc(item.id)}">Restore</button><button class="btn small danger" data-action="trash-delete" data-id="${esc(item.id)}">Delete</button></div>`).join(''):empty('Deleted classes, homework and events can be restored here.'))}
  function aboutView(){return header('About','Campus web version')+card('Campus','info',`<p class="muted" style="line-height:1.65;margin-top:0">Your KIS schedule, homework, calendar and cafeteria menu in one place. Personal data stays in this browser's local storage.</p><div class="hairline"></div><p class="small muted">PowerSchool import reads only the pages you copy into Campus. It does not receive your PowerSchool password or Chrome cookies.</p><p class="small muted">Google Classroom homework syncs after sign-in. Your tokens are stored in this browser, not on the Campus server.</p>`)}
  function settingsView(){return header('Settings','Personalize this browser')+`<div class="stack">${card('Appearance','gear',`<div class="field"><label for="appearance-select">Color mode</label><select id="appearance-select"><option value="system" ${state.appearance==='system'?'selected':''}>System</option><option value="light" ${state.appearance==='light'?'selected':''}>Light</option><option value="dark" ${state.appearance==='dark'?'selected':''}>Dark</option></select></div>`)}${card('School division','info',`<div class="field"><label for="settings-division">Division</label><select id="settings-division">${['ES','MS','HS'].map(d=>`<option ${state.division===d?'selected':''}>${d}</option>`).join('')}</select></div>`)}${card('Transfer with Mac app','sync',`<p class="small muted">Move schedules, homework, custom days, club and personal calendar events between this browser and the Mac app. Google sign-in and cached images stay on their original device. Importing replaces those items after confirmation.</p><div class="page-actions"><button class="btn" data-action="import-from-app">Import from Mac app</button><button class="btn" data-action="send-to-app">Send to Mac app</button></div>`)}${card('Local data','trash',`<p class="small muted">Your schedule, homework, notes and cached calendar stay in this browser. Clearing browser storage will erase them.</p><div class="page-actions"><button class="btn" data-action="export-data">Export backup</button><label class="btn" for="backup-file">Import backup</label><input id="backup-file" type="file" accept="application/json,.json" hidden><button class="btn danger" data-action="reset-data">Delete all local data</button></div>`)}</div>`}
  function modal(title,copy,body,wide=false){$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><div><h2 class="modal-title" id="modal-title">${esc(title)}</h2>${copy?`<p class="modal-copy">${esc(copy)}</p>`:''}</div><button class="modal-close" data-action="close" aria-label="Close">×</button></div>${body}</section></div>`;$('.modal-close').focus()}
  const close=()=>$('#modal-root').innerHTML='';
  function syncModal(){
    const ms=state.division==='MS';
    const step=(kind,title,url,copy,number)=>`<div class="step-row"><div class="step-number">${number}</div><div><div class="step-title">${title} ${draft[kind]?`<span class="pill">${kind==='week'?Object.keys(draft.week.times).length+' days of times':'10 A/B schedules'} ready</span>`:''}</div><p class="step-copy">${copy}</p><div class="page-actions" style="margin-bottom:9px"><a class="btn small" href="${url}" target="_blank" rel="noopener noreferrer">Open ${title} ${icon('external')}</a><button class="btn small" data-action="read-clipboard" data-kind="${kind}">Paste copied page</button><label class="btn small" for="file-${kind}">Or choose saved HTML</label><input class="sync-file" id="file-${kind}" type="file" data-kind="${kind}" accept=".html,.htm,text/html" hidden></div><textarea class="paste-zone ${draft[kind]?'ready':''}" data-paste="${kind}" aria-label="Paste ${title}" placeholder="Click here and press ⌘V (or Ctrl+V)"></textarea></div></div>`;
    const ready=draft.matrix&&(ms||draft.week);
    const preview=ready?`<div class="hairline"></div><div class="micro">Ready to import</div><div class="sync-preview" style="margin-top:10px">${KEYS.map(k=>`<div class="preview-day"><b>${k}</b><span>${draft.matrix.schedules[k].length} classes</span></div>`).join('')}</div><div class="field" style="margin-top:16px"><label>Known A/B day ${ms?'(this week)':'(displayed week)'} — used only if PowerSchool does not show Today is</label><div class="anchor-row"><select id="sync-weekday" aria-label="Known weekday">${DAYS.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select><select id="sync-rotation" aria-label="Known A/B day"><option>A</option><option>B</option></select></div></div>${draft.error?`<div class="notice error">${esc(draft.error)}</div>`:''}<div class="form-actions"><button class="btn primary" data-action="sync-save">Use &amp; Sync</button></div>`:draft.error?`<div class="notice error">${esc(draft.error)}</div>`:'';
    const steps=(ms?'':step('week','Week View',WEEK,'Class start and end times for Monday–Friday.',1))+step('matrix','Matrix View',MATRIX,ms?'Courses, rooms and teachers for all ten A/B days. MS times are filled in automatically and can be edited after import.':'Courses, rooms and teachers for all ten A/B days.',ms?1:2);
    modal('PowerSchool Sync',ms?'On Matrix View, press ⌘A then ⌘C. Return here and paste. Campus reads the copied page locally.':'On each page, press ⌘A then ⌘C. Return here and paste. Campus reads the copied pages locally.',steps+preview,true);
  }
  function parsePaste(kind,html){try{draft[kind]=kind==='week'?PowerSchoolImport.parseWeek(html):PowerSchoolImport.parseMatrix(html);draft.error='';syncModal();toast(`${kind==='week'?'Week View':'Matrix View'} copied successfully.`)}catch(e){draft.error=e.message;syncModal();toast(e.message)}}
  function saveSync(){try{const monday=draft.week?.monday||plusDays(dateKey(),-dayIndex(dateKey())),fallback={date:plusDays(monday,Number($('#sync-weekday')?.value||0)),day:$('#sync-rotation')?.value||'A'};const result=state.division==='MS'?PowerSchoolImport.buildMiddleSchool(draft.matrix,fallback):PowerSchoolImport.build(draft.week,draft.matrix,fallback,state.schedules);state.schedules=result.schedules;state.rotation=result.rotation;if(!state.setupComplete)state.setupStep=2;if(!save())return;close();if(state.setupComplete)go('schedule');else render();toast(`Synced all 10 A/B schedules.${result.recovered.length?' Previous times used for '+result.recovered.join(', ')+'.':''}`)}catch(e){draft.error=e.message;syncModal()}}
  function classList(key){return key.startsWith('custom:')?state.customDays[key.slice(7)]?.classes:state.schedules[key]}
  function classEditor(key,id){const c=classList(key)?.find(x=>x.id===id);modal(c?'Edit Class':'Add Class',key.startsWith('custom:')?`Custom day · ${dateLabel(key.slice(7))}`:`${DAYS[Math.floor(KEYS.indexOf(key)/2)]} · ${key.endsWith('A')?'A':'B'} Day`,`<form id="class-form" data-key="${esc(key)}" data-id="${esc(id||'')}"><div class="field"><label>Subject</label><input name="subject" value="${esc(c?.subject||'')}" required autofocus></div><div class="form-grid"><div class="field"><label>Teacher</label><input name="teacher" value="${esc(c?.teacher||'')}"></div><div class="field"><label>Room</label><input name="room" value="${esc(c?.room||'')}"></div><div class="field"><label>Starts</label><input type="time" name="start" value="${esc(c?.start||'08:25')}" required></div><div class="field"><label>Ends</label><input type="time" name="end" value="${esc(c?.end||'09:15')}" required></div></div><div class="field"><label>Color</label><input class="color-input" type="color" name="color" value="${hex(c?.color)?c.color:'#292a2c'}"></div><div class="form-actions">${c?`<button class="btn danger" type="button" data-action="class-trash" data-key="${esc(key)}" data-id="${esc(c.id)}">Delete</button>`:''}<button class="btn" type="button" data-action="close">Cancel</button><button class="btn primary">Save Class</button></div></form>`)}
  function homeworkEditor(id){const h=state.homework.find(x=>x.id===id);const due=h?.due?new Intl.DateTimeFormat('sv-SE',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(h.due)).replace(' ','T'):`${dateKey()}T23:59`;modal(h?'Homework details':'Add Homework',h?'Edit the assignment, note, color or shortcut.':'Stored only in this browser.',`<form id="homework-form" data-id="${esc(id||'')}"><div class="field"><label>Title</label><input name="title" value="${esc(h?.title||'')}" required></div><div class="form-grid"><div class="field"><label>Subject</label><input name="subject" value="${esc(h?.subject||'')}"></div><div class="field"><label>Due</label><input type="datetime-local" name="due" value="${esc(due)}" required></div></div><div class="field"><label>Shortcut URL</label><input type="url" name="url" value="${esc(h?.url||'')}" placeholder="https://…"></div><div class="field"><label>Note</label><textarea name="note">${esc(h?.note||'')}</textarea></div><div class="field"><label>Color</label><input class="color-input" type="color" name="color" value="${hex(h?.color)?h.color:'#3c82c4'}"></div><div class="form-actions">${h?`<button class="btn danger" type="button" data-action="hw-trash" data-id="${esc(h.id)}">Delete</button>`:''}<button class="btn" type="button" data-action="close">Cancel</button><button class="btn primary">${h?'Save Changes':'Add Homework'}</button></div></form>`)}
  function eventEditor(id){const e=allEvents().find(x=>x.id===id),remote=Boolean(e?.remote);modal(e?'Calendar event':'Add calendar event',remote?'School dates and effects come from the feed. Your changes stay in this browser.':'Add a local event and choose how it affects your schedule.',`<form id="event-form" data-id="${esc(id||'')}" data-remote="${remote}"><div class="field"><label>Name</label><input name="title" value="${esc(e?.title||'')}" required></div><div class="form-grid"><div class="field"><label>Starts</label><input name="start" type="date" value="${esc(e?.start||dateKey())}" ${remote?'disabled':''} required></div><div class="field"><label>Ends (optional)</label><input name="end" type="date" value="${esc(e?.end||'')}" ${remote?'disabled':''}></div></div><div class="field"><label>Type</label><select name="type" ${remote?'disabled':''}>${['info','break','half','late'].map(t=>`<option value="${t}" ${e?.type===t?'selected':''}>${typeLabel(t)}</option>`).join('')}</select></div><div class="field"><label>Color</label><input class="color-input" type="color" name="color" value="${hex(e?.color)?e.color:'#3c82c4'}"></div><div class="field"><label>Note</label><textarea name="note">${esc(e?.note||'')}</textarea></div><div class="form-actions">${e&&!remote?`<button class="btn danger" type="button" data-action="event-trash" data-id="${esc(id)}">Delete</button>`:''}<button class="btn" type="button" data-action="close">Cancel</button><button class="btn primary">Save</button></div></form>`)}
  function showDay(){const iso=dateKey(),list=classesOn(iso);modal(`Today · ${dateLabel(iso)}`,rotationAt(iso)?`${rotationAt(iso)} Day`:'No school',list.length?`<div class="schedule-list">${list.map(c=>`<div class="class-row"><div class="class-time"><strong>${esc(c.start)}</strong>${esc(c.end)}</div><div class="class-accent" style="background:${hex(c.color)?c.color:'#27282a'}"></div><div><div class="class-name">${esc(c.subject)}</div><div class="class-detail">${esc([c.teacher,c.room].filter(Boolean).join(' · '))}</div></div></div>`).join('')}</div>`:empty('No classes scheduled today.'))}
  function parseSet(text,source){const rows=[];for(const obj of text.match(/\{[^{}]{0,1000}\}/g)||[]){const f={};for(const m of obj.matchAll(/['"]?(type|start|end|name|color|id)['"]?\s*:\s*(['"])(.*?)\2/g))f[m[1]]=m[3];const start=validDate(f.start),end=validDate(f.end||f.start);if(!start||!end||end<start||!['break','half','info','late'].includes(f.type)||!f.name)continue;rows.push({id:`remote:${source}:${f.id||`${f.type}:${start}:${end}:${f.name}`}`,title:f.name,type:f.type,start,end:end===start?'':end,color:hex(f.color)?f.color:'#303234',note:'',remote:true})}return rows}
  async function refreshCalendar(silent=false){try{const sources=['global',state.division.toLowerCase()],result=await Promise.all(sources.map(async source=>{const r=await fetch(`https://kisj.space/${source}.set`,{cache:'no-store'});if(!r.ok)throw Error(`${source}.set: HTTP ${r.status}`);return parseSet(await r.text(),source)}));state.remoteEvents=result.flat();state.remoteUpdated=new Date().toISOString();save();if(page==='calendar'||page==='today')render();if(!silent)toast('School calendar updated.')}catch(e){if(!silent)toast(`Calendar update failed: ${e.message}. Saved dates are still shown.`)}}
  let menuWorkerReady;
  function menuWorker(){if(!('serviceWorker' in navigator)||!/^https?:$/.test(location.protocol))return Promise.resolve(null);return menuWorkerReady??=navigator.serviceWorker.register('./menu-sw.js').then(()=>navigator.serviceWorker.ready).then(registration=>registration.active).catch(()=>null)}
  async function cacheMenuImage(url){if(!/^https:\/\//i.test(url||''))return;const worker=await menuWorker();worker?.postMessage({type:'cache-menu-image',url})}
  async function refreshCafeteria(silent=false){try{let r;try{r=await fetch(`https://kisj.kr/our/${state.division.toLowerCase()}crawl.php`,{cache:'no-store'})}catch{throw Error('The cafeteria API blocks browser access (CORS).')}if(!r.ok)throw Error(`Cafeteria API returned HTTP ${r.status}.`);const data=await r.json(),urls=data.thisWeek?.length?data.thisWeek:data.nextWeek||[];if(!urls.length)throw Error('No menu image is published for this week or next week.');const entry=urls.find(x=>/kor|korean|kr|ko/i.test(JSON.stringify(x)))||urls[0],url=typeof entry==='string'?entry:Object.values(entry||{}).find(x=>typeof x==='string'&&x.startsWith('http'));if(!url)throw Error('The cafeteria API returned no usable image URL.');const imageURL=new URL(url,'https://kisj.kr/');if(imageURL.protocol!=='https:')throw Error('The cafeteria API returned an insecure image URL.');state.cafeteria[state.division]={image:imageURL.href,fetchedAt:new Date().toISOString()};cafeteriaStatus='';save();render();cacheMenuImage(imageURL.href);if(!silent)toast('Cafeteria menu updated.')}catch(error){cafeteriaStatus=error.message;if(page==='cafeteria')render();if(!silent)toast(cafeteriaStatus)}}
  const classroomKeys=item=>{
    const keys=new Set();
    if(item?.classroomKey)keys.add(String(item.classroomKey));
    for(const key of item?.classroomKeys||[])if(key)keys.add(String(key));
    const course=item?.courseID||item?.courseId;
    const work=item?.courseworkID||item?.courseWorkId||item?.courseworkId;
    if(course&&work)keys.add(`${course}:${work}`);
    if(item?.id)keys.add(`id:${item.id}`);
    if(item?.url)keys.add(`url:${item.url}`);
    return [...keys];
  };
  const classroomKey=item=>classroomKeys(item)[0]||item?.id;
  function putTrash(type,item,title){
    state.trash.unshift({id:uid(),type,item,title,deletedAt:new Date().toISOString()});
    if(type==='homework'){
      state.dismissedClassroomKeys ||= [];
      for(const key of classroomKeys(item))if(!state.dismissedClassroomKeys.includes(key))state.dismissedClassroomKeys.push(key);
    }
    save();
  }
  async function syncGoogleHomework(silent=false){
    if(!CampusGoogle.connected())return;
    try{
      const result=await CampusGoogle.homework();
      const incoming=new Map(result.homework.map(item=>[classroomKey(item),item]));
      const deleted=new Set([...(state.dismissedClassroomKeys || []),
        ...state.trash.filter(t=>t.type==='homework').flatMap(t=>classroomKeys(t.item))]);
      state.homework=state.homework.filter(item=>{
        if(classroomKeys(item).some(candidate=>deleted.has(candidate)))return false;
        return item.source!=='google-classroom'||incoming.has(classroomKey(item));
      });
      for(const [key,item] of incoming){
        if(!key||classroomKeys(item).some(candidate=>deleted.has(candidate)))continue;
        const old=state.homework.find(h=>classroomKey(h)===key);
        if(old)Object.assign(old,item,{note:old.note||'',color:old.color||'#3c82c4',complete:old.complete});
        else state.homework.push({...item,note:'',color:'#3c82c4',complete:false});
      }
      state.googleLastSync=result.syncedAt||new Date().toISOString();
      save();render();if(!silent)toast('Google Classroom synced.');
    }catch(error){toast(error.message||'Google Classroom sync failed.')}
  }
  window.addEventListener('campus-google-connected',()=>{state.googleReconnectRequired=false;save();render();syncGoogleHomework()});
  window.addEventListener('campus-google-error',event=>toast(event.detail));
  function restoreTrash(id){const index=state.trash.findIndex(t=>t.id===id);if(index<0)return;const t=state.trash.splice(index,1)[0];if(t.type==='homework'){
    state.homework.push(t.item);
    const restoredKeys=new Set(classroomKeys(t.item));
    state.dismissedClassroomKeys=(state.dismissedClassroomKeys || []).filter(key=>!restoredKeys.has(key));
  }if(t.type==='event')state.events.push(t.item);if(t.type==='template'){
    state.savedTemplates ||= [];state.savedTemplates.push(t.item);
  }if(t.type==='class'){const {key,block}=t.item;if(key.startsWith('custom:')){state.customDays[key.slice(7)]??={title:'Custom Day',classes:[]};state.customDays[key.slice(7)].classes.push(block)}else if(key.startsWith('all:')){
    for(const day of KEYS.filter(day=>day.endsWith(key.slice(4)))){state.schedules[day]??=[];state.schedules[day].push({...block,id:uid()})}
  }else{state.schedules[key]??=[];state.schedules[key].push(block)}}save();render();toast('Item restored.')}
  document.addEventListener('paste',e=>{const target=e.target.closest('[data-paste]');if(!target)return;e.preventDefault();parsePaste(target.dataset.paste,e.clipboardData?.getData('text/html')||e.clipboardData?.getData('text/plain')||'')});
  document.addEventListener('change',async e=>{const t=e.target;if(t.classList.contains('sync-file')){const file=t.files?.[0];if(file){if(file.size>3_000_000)return toast('HTML file is too large.');parsePaste(t.dataset.kind,await file.text())}return}if(t.id==='appearance-select'){state.appearance=t.value;save();render()}else if(t.id==='settings-division'||t.id==='division-select'){state.division=t.value;save();render();refreshCalendar(true)}else if(t.id==='custom-date'){customDate=t.value;render()}else if(t.id==='backup-file'){const file=t.files?.[0];if(!file)return;try{const value=JSON.parse(await file.text());if(value.version!==1||!Array.isArray(value.homework)||!value.schedules||typeof value.schedules!=='object')throw Error('Invalid Campus backup');if(!confirm('Replace all local Campus data with this backup?'))return;state={...defaults(),...value};save();render();toast('Backup restored.')}catch(error){toast(error.message)}}else if(t.dataset.change==='complete-hw'){const h=state.homework.find(x=>x.id===t.dataset.id);if(h){h.complete=t.checked;save();render();toast(t.checked?'Homework completed. Open Completed to undo.':'Moved back to To do.')}}else if(t.dataset.change==='select-hw'){t.checked?selection.add(t.dataset.id):selection.delete(t.dataset.id);render()}});
  document.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=new FormData(f);if(f.id==='class-form'){const key=f.dataset.key,id=f.dataset.id,start=String(d.get('start')),end=String(d.get('end'));if(minutes(end)<=minutes(start))return toast('End time must be after start time.');const list=classList(key)||[];const item={id:id||uid(),subject:String(d.get('subject')).trim(),teacher:String(d.get('teacher')).trim(),room:String(d.get('room')).trim(),start,end,color:String(d.get('color'))};if(!item.subject)return toast('Enter a subject.');const index=list.findIndex(c=>c.id===id);index>=0?list[index]=item:list.push(item);if(key.startsWith('custom:')){const iso=key.slice(7);state.customDays[iso]??={title:'Custom Day',classes:[]};state.customDays[iso].classes=list}else state.schedules[key]=list;save();close();render();toast('Class saved.')}else if(f.id==='homework-form'){const id=f.dataset.id,due=String(d.get('due'));if(!due)return toast('Choose a due date.');const url=String(d.get('url')||'').trim();if(url&&!/^https?:\/\//i.test(url))return toast('Shortcut must be an http or https address.');const item={id:id||uid(),title:String(d.get('title')).trim(),subject:String(d.get('subject')).trim(),due:new Date(`${due}:00+09:00`).toISOString(),url,note:String(d.get('note')).trim(),color:String(d.get('color')),complete:state.homework.find(h=>h.id===id)?.complete||false};const index=state.homework.findIndex(h=>h.id===id);index>=0?state.homework[index]=item:state.homework.push(item);save();close();render();toast('Homework saved.')}else if(f.id==='event-form'){const id=f.dataset.id,remote=f.dataset.remote==='true',title=String(d.get('title')).trim(),color=String(d.get('color')),note=String(d.get('note')).trim();if(remote){state.eventOverrides[id]={title,color,note}}else{const start=validDate(d.get('start')),end=d.get('end')?validDate(d.get('end')):'';if(!start||(end&&end<start))return toast('Check the event dates.');const item={id:id||uid(),title,type:String(d.get('type')),start,end,color,note,remote:false},index=state.events.findIndex(x=>x.id===id);index>=0?state.events[index]=item:state.events.push(item)}save();close();render();toast('Event saved.')}else if(f.id==='club-form'){const club={enabled:Boolean(d.get('enabled')),name:String(d.get('name')).trim(),days:d.getAll('day').map(Number),start:String(d.get('start')),end:String(d.get('end'))};if(minutes(club.end)<=minutes(club.start))return toast('Club end time must be after its start.');state.club=club;save();render();toast('Club saved.')}});
  document.addEventListener('click',async e=>{const t=e.target.closest('[data-nav],[data-action],#settings-button,#mobile-menu');if(!t)return;if(t.dataset.nav){go(t.dataset.nav);return}if(t.id==='settings-button'){go('settings');return}if(t.id==='mobile-menu'){$('.sidebar').classList.toggle('open');return}const a=t.dataset.action,id=t.dataset.id,key=t.dataset.key;switch(a){
    case 'close':close();break;
    case 'import-from-app':try{CampusTransfer.requestAppExport()}catch(error){toast(error.message)}break;
    case 'send-to-app':try{CampusTransfer.sendToApp(state)}catch(error){toast(error.message)}break;
    case 'transfer-apply':{
      if(!pendingTransfer)break;
      try{
        const previous=state;
        state=CampusTransfer.toWebState(pendingTransfer,state);
        state.setupComplete=true;
        state.setupStep=2;
        if(!save()){state=previous;break}
        CampusGoogle.disconnect();
        try{CampusTransfer.markUsed(pendingTransferNonce)}catch{}
        pendingTransfer=null;pendingTransferNonce=null;close();go('homework');toast('Mac data imported. Connect Google Classroom again to resume syncing.');
      }catch(error){toast(error.message)}
      break;
    }
    case 'setup-division':state.division=t.dataset.division;state.club.enabled=state.division==='MS';save();render();break;
    case 'setup-next':if((Number(state.setupStep)||0)===0)state.club.enabled=state.division==='MS';state.setupStep=Math.min(2,(Number(state.setupStep)||0)+1);save();render();break;
    case 'setup-back':state.setupStep=Math.max(0,(Number(state.setupStep)||0)-1);save();render();break;
    case 'setup-skip':state.setupStep=2;save();render();break;
    case 'setup-finish':state.setupComplete=true;state.setupStep=2;save();go('today');refreshCafeteria(true);break;
    case 'show-day':showDay();break;
    case 'sync':draft={week:null,matrix:null,error:''};syncModal();break;
    case 'read-clipboard':try{const items=await navigator.clipboard.read();let html='';for(const item of items){if(item.types.includes('text/html')){html=await(await item.getType('text/html')).text();break}if(item.types.includes('text/plain'))html=await(await item.getType('text/plain')).text()}parsePaste(t.dataset.kind,html)}catch{toast('Clipboard access was blocked. Click the paste box and press ⌘V or Ctrl+V.')}break;
    case 'sync-save':saveSync();break;
    case 'manual-start':state.schedules.MA??=[];save();render();break;
    case 'schedule-tab':scheduleMode=t.dataset.mode;if(scheduleMode==='regular')rotationView=t.dataset.day;render();break;
    case 'mode':scheduleMode=t.dataset.mode;render();break;
    case 'weekday':weekdayView=Number(t.dataset.index);render();break;
    case 'rotation-view':rotationView=t.dataset.day;render();break;
    case 'class-new':classEditor(KEYS[weekdayView*2+(rotationView==='B'?1:0)]);break;
    case 'class-edit':classEditor(key,id);break;
    case 'class-trash':{const list=classList(key),index=list?.findIndex(c=>c.id===id);if(index>=0){const block=list.splice(index,1)[0];putTrash('class',{key,block},block.subject);close();render();toast('Class moved to Trash.')}break}
    case 'anchor-save':{const date=$('#anchor-date').value,day=$('#anchor-day').value;if(dayIndex(date)>4)return toast('Choose a Monday–Friday date.');state.rotation={date,day,lastSyncedAt:state.rotation?.lastSyncedAt||null};save();render();toast('A/B reference day saved.');break}
    case 'custom-copy':state.customDays[customDate]={title:'Custom Day',classes:classesOn(customDate).filter(c=>c.id!=='club').map(c=>({...c,id:uid()}))};save();render();break;
    case 'custom-add':classEditor(`custom:${customDate}`);break;
    case 'custom-remove':if(confirm('Remove this custom day and use the normal schedule?')){delete state.customDays[customDate];save();render()}break;
    case 'hw-new':homeworkEditor();break;
    case 'hw-edit':homeworkEditor(id);break;
    case 'hw-tab':homeworkTab=t.dataset.tab;render();break;
    case 'select-start':selecting=true;selection.clear();render();break;
    case 'select-end':selecting=false;selection.clear();render();break;
    case 'hw-trash':{const index=state.homework.findIndex(h=>h.id===id);if(index>=0){const item=state.homework.splice(index,1)[0];putTrash('homework',item,item.title);selection.delete(id);close();render();toast('Homework moved to Trash.')}break}
    case 'bulk-done':for(const h of state.homework)if(selection.has(h.id))h.complete=true;selecting=false;selection.clear();save();render();break;
    case 'bulk-trash':state.homework=state.homework.filter(h=>{if(!selection.has(h.id))return true;putTrash('homework',h,h.title);return false});selecting=false;selection.clear();save();render();break;
    case 'bulk-color':modal('Homework Color','Apply one color to selected homework.',`<div class="field"><label>Color</label><input class="color-input" id="bulk-color" type="color" value="#3c82c4"></div><div class="form-actions"><button class="btn" data-action="close">Cancel</button><button class="btn primary" data-action="bulk-color-save">Apply</button></div>`);break;
    case 'bulk-color-save':{const color=$('#bulk-color').value;for(const h of state.homework)if(selection.has(h.id))h.color=color;save();close();render();break}
    case 'google-info':CampusGoogle.connected()?syncGoogleHomework():CampusGoogle.connect();break;
    case 'month-prev':case 'month-next':{const [year,month]=monthView.split('-').map(Number);monthView=new Date(Date.UTC(year,month-1+(a==='month-next'?1:-1),1)).toISOString().slice(0,7);render();break}
    case 'month-today':monthView=dateKey().slice(0,7);render();break;
    case 'calendar-refresh':refreshCalendar();break;
    case 'event-new':eventEditor();break;
    case 'event-edit':eventEditor(id);break;
    case 'event-trash':{const index=state.events.findIndex(x=>x.id===id);if(index>=0){const item=state.events.splice(index,1)[0];putTrash('event',item,item.title);close();render()}break}
    case 'cafe-refresh':refreshCafeteria();break;
    case 'trash-restore':restoreTrash(id);break;
    case 'trash-delete':state.trash=state.trash.filter(x=>x.id!==id);save();render();break;
    case 'trash-clear':if(confirm('Permanently delete everything in Trash?')){state.trash=[];save();render()}break;
    case 'reset-data':if(confirm('Delete all Campus data saved in this browser, including Google sign-in? This cannot be undone.')){localStorage.removeItem(KEY);CampusGoogle.disconnect();state=defaults();go('today');toast('Local data deleted.')}break;
    case 'export-data':{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`campus-backup-${dateKey()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),5000);break}
  }});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#modal-root').firstChild)close()});
  window.addEventListener('hashchange',()=>{const next=location.hash.slice(1);if((pages.some(p=>p[0]===next)||next==='settings')&&next!==page){page=next;render()}});
  matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.appearance==='system')theme()});
  render();
  function presentTransfer(receivedTransfer){
    if(receivedTransfer?.error){toast(receivedTransfer.error);return}
    if(!receivedTransfer?.snapshot)return;
    pendingTransfer=receivedTransfer.snapshot;
    pendingTransferNonce=receivedTransfer.nonce;
    const snapshot=pendingTransfer;
    const count=Object.values(snapshot.schedules).reduce((total,classes)=>total+classes.length,0);
    modal('Import from Mac app?',
      `${receivedTransfer.unrequested?'This browser did not start the transfer. Continue only if you just approved sending from your Mac. ':''}This will replace your browser schedules, homework, Trash, custom days, club and personal calendar events. The browser's Google Classroom sign-in will be disconnected; sign in again here after import.`,
      `<div class="notice">${count} classes · ${snapshot.homework.length} homework items · ${snapshot.trash?.length || 0} Trash items · ${snapshot.events.length} calendar events · ${Object.keys(snapshot.customDays).length} custom days</div><div class="form-actions"><button class="btn" data-action="close">Cancel</button><button class="btn primary" data-action="transfer-apply">Replace browser data</button></div>`);
  }
  presentTransfer(CampusTransfer.takeIncoming());
  if(CampusTransfer.hasPending())modal('Receiving Mac data…',
    'Campus is retrieving your encrypted transfer. This can take up to a minute.',
    '<div class="notice">Keep this tab open while the transfer arrives.</div>');
  CampusTransfer.receivePending().then(received=>{
    if(received){close();presentTransfer(received)}
  });
  if(!state.remoteUpdated||Date.now()-new Date(state.remoteUpdated).getTime()>3600000)refreshCalendar(true);
  menuWorker().then(worker=>{if(worker)Object.values(state.cafeteria).forEach(menu=>cacheMenuImage(menu?.image))});
  if(state.setupComplete)refreshCafeteria(true);
  if(state.setupComplete&&CampusGoogle.connected())syncGoogleHomework(true);
  setInterval(()=>{if(page==='today'&&!$('#modal-root').firstChild)render()},1000);
  setInterval(()=>{if(!state.remoteUpdated||Date.now()-new Date(state.remoteUpdated).getTime()>3600000)refreshCalendar(true)},60000);
  setInterval(()=>{if(CampusGoogle.connected())syncGoogleHomework(true)},3600000);
  setInterval(()=>{if(state.setupComplete)refreshCafeteria(true)},3600000);
})();
